# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0014_missing_closed_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='dist_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfers.District'),
        ),
    ]
