# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('comm_area_no', models.IntegerField(null=True)),
                ('side', models.CharField(max_length=50, null=True)),
                ('total_pop', models.IntegerField(null=True)),
                ('pct_black', models.FloatField(null=True)),
                ('pct_white', models.FloatField(null=True)),
                ('pct_latino', models.FloatField(null=True)),
                ('pct_poor', models.FloatField(null=True)),
                ('age_under_5', models.IntegerField(null=True)),
                ('age_5_to_9', models.IntegerField(null=True)),
                ('age_10_to_14', models.IntegerField(null=True)),
                ('age_15_to_17', models.IntegerField(null=True)),
                ('age_18_to_19', models.IntegerField(null=True)),
            ],
        ),
    ]
