# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:14
from __future__ import unicode_literals
from django.db import migrations
import csv
from cps_migration.settings import BASE_DIR 
from geos.models import CommArea

### START CONFIG ###
data_dir = BASE_DIR + '/data/source/'
comm_area_id_path = data_dir + 'CommAreas.csv'
### END CONFIG ###

def add_ids(apps,schema_editor):
    comm_area_csv = [x for x in csv.DictReader(open(comm_area_id_path))]
    for comm_area in comm_area_csv:
        ca_lower_split = comm_area['COMMUNITY'].lower().split()
        cas = [ x for x in CommArea.objects.all() if x.name.lower().split() == ca_lower_split]
        if len(cas) != 1:
            import ipdb; ipdb.set_trace()
        ca = cas[0]
        ca.comm_area_no = comm_area['AREA_NUM_1']
        print ca.name, ca.comm_area_no
        ca.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0001_initial'),
        ('transfers','0009_comm_areas')
    ]

    operations = [
            migrations.RunPython(add_ids),
    ]
