# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:44
from __future__ import unicode_literals
from django.db import migrations
import csv
from cps_migration.settings import BASE_DIR
from geos.models import CommArea
from tcr_tools.typify import floatify

### START CONFIG ###
data_dir = BASE_DIR + '/data/source/'
race_filename = 'B03002_moe.csv'
poverty_filename = 'B17026_moe.csv'
age_filename = 'B01001_moe.csv'
### END CONFIG ###


def add_race_to_comm_areas(apps,schema_editor):
    race_file_path = data_dir + race_filename
    race_csv = csv.DictReader(open(race_file_path))
    for row in race_csv:
        comm_area = CommArea.objects.get(comm_area_no=row['Community Area ID'])
        comm_area.pct_black = floatify(row['B03002_004E: Not Hispanic or Latino:!!Black or African American alone'])/\
                floatify(row['B03002_001E: Total:'])
        comm_area.pct_white = floatify(row['B03002_003E: Not Hispanic or Latino:!!White alone'])/\
                floatify(row['B03002_001E: Total:'])
        comm_area.pct_latino = floatify(row['B03002_012E: Hispanic or Latino:'])/\
                floatify(row['B03002_001E: Total:'])
        comm_area.save()
                


def add_poverty_to_comm_areas(apps,schema_editor):
    poverty_file_path = data_dir + poverty_filename
    poverty_csv = csv.DictReader(open(poverty_file_path))
    for row in poverty_csv:
        comm_area = CommArea.objects.get(comm_area_no=row['Community Area ID'])
        comm_area.pct_poor = sum([floatify(x) for x in [row['B17026_002E: Under .50'],row['B17026_003E: .50 to .74'],row['B17026_004E: .75 to .99']]])/\
                floatify(row['B17026_001E: Total:'])
        comm_area.save()


def add_ages_to_comm_areas(apps,schema_editor):
    age_file_path = data_dir + age_filename
    age_csv = csv.DictReader(open(age_file_path))
    for row in age_csv:
        comm_area = CommArea.objects.get(comm_area_no=row['Community Area ID'])
        comm_area.age_under_5 = floatify(row['B01001_003E: Male:!!Under 5 years']) + floatify(row['B01001_027E: Female:!!Under 5 years'])
        comm_area.age_5_to_9 = floatify(row['B01001_004E: Male:!!5 to 9 years']) + floatify(row['B01001_028E: Female:!!5 to 9 years'])
        comm_area.age_10_to_14 = floatify(row['B01001_005E: Male:!!10 to 14 years']) + floatify(row['B01001_029E: Female:!!10 to 14 years'])
        comm_area.age_15_to_17 = floatify(row['B01001_006E: Male:!!15 to 17 years']) + floatify(row['B01001_030E: Female:!!15 to 17 years'])
        comm_area.age_18_to_19 = floatify(row['B01001_007E: Male:!!18 and 19 years']) + floatify(row['B01001_031E: Female:!!18 and 19 years'])
        
        comm_area.total_pop = floatify(row['B01001_001E: Total:'])

        comm_area.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0002_comm_area_ids')
    ]

    operations = [
            migrations.RunPython(add_race_to_comm_areas),
            migrations.RunPython(add_poverty_to_comm_areas),
            migrations.RunPython(add_ages_to_comm_areas)
    ]
