# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:35
from __future__ import unicode_literals
from django.db import migrations
from cps_migration.settings import BASE_DIR
from geos.models import CommArea
import json

### START CONFIG ###
data_dir = BASE_DIR + '/data/source/'
cas_sides_path = data_dir + 'sides.json'
### END CONFIG ###

def add_sides_to_cas(apps,schema_editor):
    side_cas = json.load(open(cas_sides_path))
    for item in side_cas:
        for ca in item['cas']:
            comm_area = CommArea.objects.get(comm_area_no=ca)
            comm_area.side = item['side']
            comm_area.save()



class Migration(migrations.Migration):

    dependencies = [
        ('geos', '0003_census'),
    ]

    operations = [
            migrations.RunPython(add_sides_to_cas)
    ]
