# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=30, null=True)),
                ('rcdts', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('k12', models.IntegerField(null=True)),
                ('housed', models.IntegerField(null=True)),
                ('low_income', models.IntegerField(null=True)),
                ('male', models.IntegerField(null=True)),
                ('female', models.IntegerField(null=True)),
                ('hispanic', models.IntegerField(null=True)),
                ('am_ind', models.IntegerField(null=True)),
                ('asian', models.IntegerField(null=True)),
                ('black', models.IntegerField(null=True)),
                ('opi', models.IntegerField(null=True)),
                ('white', models.IntegerField(null=True)),
                ('multiple_races', models.IntegerField(null=True)),
                ('pre_k', models.IntegerField(null=True)),
                ('kind', models.IntegerField(null=True)),
                ('first', models.IntegerField(null=True)),
                ('second', models.IntegerField(null=True)),
                ('third', models.IntegerField(null=True)),
                ('fourth', models.IntegerField(null=True)),
                ('fifth', models.IntegerField(null=True)),
                ('sixth', models.IntegerField(null=True)),
                ('seventh', models.IntegerField(null=True)),
                ('eighth', models.IntegerField(null=True)),
                ('ninth', models.IntegerField(null=True)),
                ('tenth', models.IntegerField(null=True)),
                ('eleventh', models.IntegerField(null=True)),
                ('twelfth', models.IntegerField(null=True)),
                ('administrator', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=12, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('grades_served', models.CharField(max_length=20, null=True)),
                ('rec_type', models.CharField(max_length=40, null=True)),
                ('st_rep', models.IntegerField(null=True)),
                ('st_sen', models.IntegerField(null=True)),
                ('fed_cong', models.IntegerField(null=True)),
                ('cat', models.CharField(max_length=5, null=True)),
                ('nces_id', models.CharField(max_length=20, null=True)),
                ('cps_id', models.IntegerField(null=True)),
                ('comm_area_name', models.CharField(max_length=40, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('cps_closed', models.NullBooleanField()),
                ('attendance_type', models.CharField(max_length=40, null=True)),
                ('comm_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geos.CommArea')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_no', models.IntegerField(null=True)),
                ('school_year', models.IntegerField(null=True)),
                ('fte', models.FloatField(null=True)),
                ('from_home_rcdts', models.CharField(max_length=20, null=True)),
                ('from_serving_rcdts', models.CharField(max_length=20, null=True)),
                ('to_home_rcdts', models.CharField(max_length=20, null=True)),
                ('to_serving_rcdts', models.CharField(max_length=20, null=True)),
                ('enrollment_date', models.DateField(null=True)),
                ('exit_date', models.DateField(null=True)),
                ('exit_code', models.IntegerField(null=True)),
                ('exit_desc', models.CharField(max_length=200, null=True)),
                ('from_home_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_home_school', to='transfers.School')),
                ('from_serving_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_serving_school', to='transfers.School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfers.Student')),
                ('to_home_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_home_school', to='transfers.School')),
                ('to_serving_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_serving_school', to='transfers.School')),
            ],
        ),
    ]
