# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:27
from __future__ import unicode_literals
from django.db import migrations, transaction
from cps_migration.settings import BASE_DIR
import csv
from tcr_tools.typify import intify
from transfers.models import School

### START CONFIG ###
data_dir = BASE_DIR + '/data/processed/'
enrollment_filename = data_dir + 'closed_schools.csv' 
### END CONFIG ###

@transaction.atomic
def load_schools(apps,schema_editor):
    print('loading schools')
    enrollment_csv = csv.DictReader(open(enrollment_filename))
    for row in enrollment_csv:
        try:
            rcdts = row['Reg/Cty/ Dist/Type'].replace('-','') + row['School']
            school, created = School.objects.get_or_create(rcdts=rcdts,name=row['School Name'])
            school.county = row['County']
            school.cat = row['CAT']
            school.rcdts = rcdts
            school.name = row['School Name']
            school.k12 = intify(row['K-12'])
            school.housed = intify(row['Housed [PK -12]'])
            school.low_income = intify(row['Low Income'])
            school.male = intify(row['Male'])
            school.female = intify(row['Female'])
            school.hispanic = intify(row['Hispanic'])
            school.am_ind = intify(row['Am. Indian'])
            school.asian = intify(row['Asian'])
            school.black = intify(row['Black'])
            school.opi = intify(row['OPI'])
            school.white = intify(row['White'])
            school.multiple_races = intify(row['2/More'])
            school.pre_k = intify(row['PreK'])
            school.kind = intify(row['K'])
            school.first = intify(row['1'])
            school.second = intify(row['2'])
            school.third = intify(row['3'])
            school.fourth = intify(row['4'])
            school.fifth = intify(row['5'])
            school.sixth = intify(row['6'])
            school.seventh = intify(row['7'])
            school.eighth = intify(row['8'])
            school.ninth = intify(row['9'])
            school.tenth = intify(row['10'])
            school.eleventh = intify(row['11'])
            school.twelfth = intify(row['12'])
            school.administrator = row['Principal']
            school.address = row['Address']
            school.city = row['City']
            school.zip_code = row['Zip']
            school.cps_closed = True   
            school.save()
        except Exception, e:
            print e
            import ipdb; ipdb.set_trace()



class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transfers'),
    ]

    operations = [
            migrations.RunPython(load_schools)
    ]
