# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:07
from __future__ import unicode_literals
from django.db import migrations
from transfers.models import School
from geos.models import CommArea

def lookup_cps_schools(apps,schema_editor):
    cps_schools = School.objects.filter(comm_area_name__isnull=False)
    for cps_school in cps_schools:
        try:
            comm_area, created = CommArea.objects.get_or_create(name=cps_school.comm_area_name)
        except Exception, e:
            print e
            import ipdb; ipdb.set_trace()
        if created:
            comm_area.save()
        cps_school.comm_area = comm_area
        cps_school.save()


class Migration(migrations.Migration):

    dependencies = [
            ('transfers','0007_add_cps_stuff'),
    ]

    operations = [
            migrations.RunPython(lookup_cps_schools)
    ]
