# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:50
from __future__ import unicode_literals
from django.db import migrations
import csv
from cps_migration.settings import BASE_DIR
from transfers.models import School

### START CONFIG ###
data_dir = BASE_DIR + '/data/source/'
att_file_path = data_dir + 'Neighborhood boundaries.csv'
logfile_path = '/tmp/cps_id_fails.csv'
### END CONFIG ###

def load_att_types(apps,schema_editor):
    infile = open(att_file_path)
    incsv = csv.DictReader(infile)
    logfile = open(logfile_path,'w')
    logfile_csv = csv.DictWriter(logfile,incsv.fieldnames)
    logfile_csv.writeheader()
    for row in incsv:
        try:
            school = School.objects.get(cps_id=row['SCHOOL_ID'])
            school.attendance_type = row['BOUNDARY_SY1617']
            school.save()
        except Exception, e:
            print e, row
            logfile_csv.writerow(row)
    logfile.close()

class Migration(migrations.Migration):

    dependencies = [
            ('transfers','0009_comm_areas'),
    ]

    operations = [
            migrations.RunPython(load_att_types)
    ]
