# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:35
from __future__ import unicode_literals
from transfers.models import Transfer, School
from django.db import migrations

def fixFromHomeTransfers(apps,schema_editor):
    print('getting transfers')
    transfers = [x for x in Transfer.objects.all()]

    print('getting busted transfers')
    busted_from_home_lookups = [x for x in transfers if x.from_home_rcdts and not x.from_home_school]
    busted_from_serving_lookups = [x for x in transfers if x.from_serving_rcdts and not x.from_serving_school]
    fixes = []

    print('fixing busted transfers')
    for transfer in busted_from_home_lookups:
        try:
            from_home_schools = School.objects.filter(rcdts=transfer.from_home_rcdts)
            if from_home_schools:
                transfer.from_home_school = from_home_schools[0]
                transfer.save()
                print('fixed busted transfer id: ' + str(transfer.id))
                fixes.append(transfer)
        except Exception, e:
            import ipdb; ipdb.set_trace()

    for transfer in busted_from_serving_lookups:
        try:
            from_serving_schools = School.objects.filter(rcdts=transfer.from_serving_rcdts)
            if from_serving_schools:
                transfer.from_serving_school = from_serving_schools[0]
                transfer.save()
                print('fixed busted transfer id: ' + str(transfer.id))
                fixes.append(transfer)
        except Exception, e:
            import ipdb; ipdb.set_trace()

    print('all set. inspect fixes:')
    print [fix.__dict__ for fix in fixes]


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0011_add_attendance_type'),
    ]

    operations = [
            migrations.RunPython(fixFromHomeTransfers),
    ]
