# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:35
from __future__ import unicode_literals
from transfers.models import Transfer, School
from django.db import migrations

print('getting transfers')
transfers = [x for x in Transfer.objects.all()]

print('getting busted transfers')
busted_from_home_lookups = [x for x in transfers if x.from_home_rcdts and not x.from_home_school]
fixes = []

def fixFromHomeTransfers(apps,schema_editor):
    print('fixing busted transfers')
    for transfer in busted_from_home_lookups:
        try:
            from_home_schools = School.objects.filter(rcdts=transfer.from_home_rcdts)
            if from_home_schools:
                transfer.from_home_school = from_home_schools[0]
                transfer.save()
                print('fixed busted transfer id: ' + str(transfer.id))
                fixes.append(transfer)
        except Exception, e:
            import ipdb; ipdb.set_trace()
    print('all set. inspect fixes:')
    import ipdb; ipdb.set_trace()


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0011_add_attendance_type'),
    ]

    operations = [
            migrations.RunPython(fixFromHomeTransfers),
    ]
