# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 21:19
from __future__ import unicode_literals
from django.db import migrations
from transfers.models import School

def null_and_delete(apps,schema_editor):
    """
    per kb's slack 10/27
    """
    ycchs = School.objects.get(name='Youth Connections Charter HS')
    ycchs.cps_id = None
    ycchs.save()

    yshah = School.objects.get(name='YCCS-Sullivan House Alt HS')
    yshah.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0012_fix_transfer_lookups'),
    ]

    operations = [
            migrations.RunPython(null_and_delete)
    ]
