# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:18
from __future__ import unicode_literals
from django.db import migrations
import csv
from transfers.models import School, District
from cps_migration.settings import BASE_DIR

### START CONFIG ###
data_dir = BASE_DIR + '/data/source/'
district_file_path = data_dir + 'schools_to_districts.csv'
### END CONFIG ###

def load_districts(apps,schema_editor):
    district_file = open(district_file_path)
    district_csv = [x for x in csv.DictReader(district_file)]
    
    for row in district_csv:
        try:
            rcdts = row['SCHOOL ID (R-C-D-T-S)']
            if len(rcdts) == 14:
                rcdts = '0' + rcdts
            schools = School.objects.filter(rcdts=rcdts)
            if len(schools) > 1:
                print rcdts, ','.join([x.name for x in schools])
            elif len(schools) == 0:
                print 'lookup fail:', rcdts
            else:
                school = schools[0]
            district, created = District.objects.get_or_create(name=row['DISTRICT NAME'].rstrip())
            school.district = district
            school.save()
            if created:
                district.save()
        except Exception, e:
            import ipdb; ipdb.set_trace()

class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0014_missing_closed_school'),
    ]

    operations = [
            migrations.RunPython(load_districts)
    ]
